var tableauQuestion = [
    {   question : "Hvis du kører 80 KM/T og du nærmer dig et boligområde skal du:",
        propositionA : "Øge din hastighed",
        propositionB : "Holde nuværrende hastighed, så længe der ikke er andre bilister eller fodgængere",
        propositionC : "Sænke din hastighed",
        propositionD : "Holde din hastighed",
        reponse : "C"},
		
    {   question : "Du drejer til venstre, og ser en fodgænger i fodgængerfeltet, hvem har lov til at fortsætte?",
        propositionA : "Fodgængeren, da de kan krydse vejen ved alle lys.",
        propositionB : "Bilen, da den har grønt",
        propositionC : "Fodgængeren, da de krydse vejen ved grønt",
        propositionD : "Bilen, da den har førsteret i trafikken.",
        reponse : "C"},
		
    {   question : "Hvis der ikke er skiltning, må du køre ____ i et boligområde.",
        propositionA : "50 KM/T",
        propositionB : "55 KM/T",
        propositionC : "65 KM/T",
        propositionD : "70 KM/T",
        reponse : "A"},
	
	{   question : "Før du skifter bane skal du:",
        propositionA : "Kigge i dine sidespejle",
        propositionB : "Kigge i dine blinde vinkler",
        propositionC : "Signalere hvad du vil",
        propositionD : "Alt overstående",
        reponse : "D"},
		
	{   question : "Ved hvilken procent, bliver du anset som beruset?",
        propositionA : "0.5‰",
        propositionB : "0.18‰",
        propositionC : "0.8‰",
        propositionD : "0.6‰",
        reponse : "A"},
		
	{   question : "Du skal holde ind og stoppe, når der kommer et udrykningskøretøj, medmindre:",
        propositionA : "At du har travlt",
        propositionB : "At der er nok plads i en anden vejbane",
        propositionC : "Du er i en skolezone",
        propositionD : "Du holder i et vejkryds",
        reponse : "D"},
	
	{   question : "Førsteret til udrykningskøretøjer",
        propositionA : "Gives altid",
        propositionB : "Gives, hvis de kører med tændte blink på taget.",
        propositionC : "Gives, hvis de kører med sirener og tændte blink på taget.",
        propositionD : "Gives, hvis de bruger sirenen uden blink.",
        reponse : "C"},
		
	{   question : "Hvad skal du gøre, når du passerer en medkørende bilist?",
        propositionA : "Følge tæt",
        propositionB : "Forlade vejen ved næste afkørsel",
        propositionC : "Blinke ud, og overhale i den anden vejbane",
        propositionD : "Køre hurtigere end fartgrænsen",
        reponse : "C"},
		
	{   question : "Du kører på en motorvej hvor fartgrænsen er 110 KM/T. Det meste af trafikken kører med 120 KM/T, hvad hastighed skal du køre?",
        propositionA : "80 KM/T",
        propositionB : "120 KM/T",
        propositionC : "50 KM/T",
        propositionD : "110 KM/T",
        reponse : "D"},
		
	{   question : "Når du overhæler en anden bilist, er det vigtigt at du:",
        propositionA : "Sænker farten",
        propositionB : "Tjekker dine spejle",
        propositionC : "Kigger på den anden chauffør",
        propositionD : "Accelerere",
        reponse : "D"},
]
